// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/metro-digital-inner-source/errorbudget-grafana-controller/grafana-controller/client/elastic (interfaces: IClient)

// Package elastic is a generated GoMock package.
package elastic

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	elastic "github.com/metro-digital-inner-source/errorbudget-grafana-controller/grafana-controller/model/elastic"
)

// MockIClient is a mock of IClient interface.
type MockIClient struct {
	ctrl     *gomock.Controller
	recorder *MockIClientMockRecorder
}

// MockIClientMockRecorder is the mock recorder for MockIClient.
type MockIClientMockRecorder struct {
	mock *MockIClient
}

// NewMockIClient creates a new mock instance.
func NewMockIClient(ctrl *gomock.Controller) *MockIClient {
	mock := &MockIClient{ctrl: ctrl}
	mock.recorder = &MockIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIClient) EXPECT() *MockIClientMockRecorder {
	return m.recorder
}

// CreateIndex mocks base method.
func (m *MockIClient) CreateIndex(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIndex", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateIndex indicates an expected call of CreateIndex.
func (mr *MockIClientMockRecorder) CreateIndex(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIndex", reflect.TypeOf((*MockIClient)(nil).CreateIndex), arg0, arg1)
}

// DeleteSloHistory mocks base method.
func (m *MockIClient) DeleteSloHistory(arg0 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSloHistory", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSloHistory indicates an expected call of DeleteSloHistory.
func (mr *MockIClientMockRecorder) DeleteSloHistory(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSloHistory", reflect.TypeOf((*MockIClient)(nil).DeleteSloHistory), arg0)
}

// GetIndices mocks base method.
func (m *MockIClient) GetIndices() ([]*elastic.Index, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIndices")
	ret0, _ := ret[0].([]*elastic.Index)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIndices indicates an expected call of GetIndices.
func (mr *MockIClientMockRecorder) GetIndices() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIndices", reflect.TypeOf((*MockIClient)(nil).GetIndices))
}
